# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Record.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1274, 673)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sqlCentralWidget = QtWidgets.QWidget(Form)
        self.sqlCentralWidget.setMinimumSize(QtCore.QSize(1256, 655))
        self.sqlCentralWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sqlCentralWidget.setObjectName("sqlCentralWidget")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.sqlCentralWidget)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.tblSql = QtWidgets.QTableWidget(self.sqlCentralWidget)
        self.tblSql.setObjectName("tblSql")
        self.tblSql.setColumnCount(4)
        self.tblSql.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblSql.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblSql.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblSql.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblSql.setHorizontalHeaderItem(3, item)
        self.tblSql.horizontalHeader().setCascadingSectionResizes(False)
        self.tblSql.horizontalHeader().setSortIndicatorShown(False)
        self.tblSql.horizontalHeader().setStretchLastSection(False)
        self.verticalLayout_8.addWidget(self.tblSql)
        self.widget = QtWidgets.QWidget(self.sqlCentralWidget)
        self.widget.setMinimumSize(QtCore.QSize(0, 0))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget.setObjectName("widget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btnShowAll = QtWidgets.QPushButton(self.widget)
        self.btnShowAll.setMinimumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnShowAll.setFont(font)
        self.btnShowAll.setObjectName("btnShowAll")
        self.horizontalLayout_6.addWidget(self.btnShowAll)
        self.btnLoadSql = QtWidgets.QPushButton(self.widget)
        self.btnLoadSql.setMinimumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnLoadSql.setFont(font)
        self.btnLoadSql.setObjectName("btnLoadSql")
        self.horizontalLayout_6.addWidget(self.btnLoadSql)
        self.btnDelete = QtWidgets.QPushButton(self.widget)
        self.btnDelete.setMinimumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnDelete.setFont(font)
        self.btnDelete.setObjectName("btnDelete")
        self.horizontalLayout_6.addWidget(self.btnDelete)
        self.verticalLayout_8.addWidget(self.widget, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout.addWidget(self.sqlCentralWidget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        item = self.tblSql.horizontalHeaderItem(0)
        item.setText(_translate("Form", "记录时间"))
        item = self.tblSql.horizontalHeaderItem(1)
        item.setText(_translate("Form", "测试人员生日"))
        item = self.tblSql.horizontalHeaderItem(2)
        item.setText(_translate("Form", "姓名"))
        item = self.tblSql.horizontalHeaderItem(3)
        item.setText(_translate("Form", "性别"))
        self.btnShowAll.setText(_translate("Form", "显示全部记录"))
        self.btnLoadSql.setText(_translate("Form", "读取"))
        self.btnDelete.setText(_translate("Form", "删除"))
